name: 'Label Checker'
author: 'Shingo Sato <shinsugar@gmail.com>'
description: 'Automated labels checking for Pull requests'
inputs:
  required_any:
    description: 'At least one of these comma separated labels should be present on all Pull requests'
    required: false
  required_all:
    description: 'All of these comma separated labels must be present on all Pull requests'
    required: false
  required_oneof:
    description: 'At only one of these comma separated labels should be present on all Pull requests'
    required: false
  banned:
    description: 'None of these comma separated labels can be present on all Pull requests'
    required: false
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN for setting Pull Request status.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check'
  color: 'green'
