name: Test

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, reopened]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run pack
      - uses: ./
        with: 
          requiredAll: 'approved'
