name: Test

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, reopened]
    paths:
      - '.github/**'
      - action.yml
      - 'dist/**'
      - package.json

jobs:
  check-label:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          required_all: 'approved'
          required_oneof: 'patch,minor,major'
          pullrequest_state: "pending"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
