name: Test

on:
  pull_request:
    types: [opened, labeled, unlabeled, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        requiredAll: 'approved'
